<form action="" method="POST">    
    <label 
        class="labelForm">Usuario:</label>
    <input 
        name="user" 
        type="text" 
        placeholder="Usuario" 
        autofocus
        autocomplete="off">
    <label 
        class="labelForm">Contraseña:</label>
    <input 
        name="password" 
        type="password" 
        placeholder="Contraseña">
    <input 
        type="submit" 
        value="Enviar">
</form>